import type { URecord } from "@blazyts/better-standard-library";
import type { ServiceBase, ServiceDefault } from "src/services/main";

export type HookLog = {
    name: string,
    startTime: number, 
    endTime: number,
    got: URecord,
    returned: URecord
}

// note for websocket requests since they are long lived, they are stored as normal but share an additional field called connection, which is an id generated for a connection , also since websocket messages do not have a response they just have a request
export type Log = {
    requestId: string; // -> unique id for each request, can be generated by the framework and passed to the logger, this is helpful both for the cinsumer of the logs and the ogger himself since it makes logging when doing multiarallelism easy and also helps with log correlation in case the logs are sent to an external system, in the system this is apssed between each hook and to the request hander too
    requestReceived: URecord & { recievedAt: Date }
    responseSent: URecord & { sentAt: Date }
    hooks: {
        beforeHandler: HookLog[]
        afterHandler: HookLog[]
    },
    connectionId?: string
}

export interface ILogger extends ServiceBase<{collectLogsFrom: ("beforeHandlerHooks" | "afterHandlerHooks" | "requestHandler" | "services")[]}> {
    logRequest(req: Request): Promise<Result>
    logHookExecution(hookType: "beforeHandler" | "afterHandler", log: HookLog): Promise<Result>
    logResponse(res: Response): Promise<Result>
}